#!/usr/bin/env bash
set -euo pipefail

# ============================================
# Self-Hosted CV — One-Click Install Script
# ============================================
# Usage:
#   curl -fsSL https://raw.githubusercontent.com/ninejuan/self-hosted-cv/main/install.sh | bash
#   or:
#   wget -qO- https://raw.githubusercontent.com/ninejuan/self-hosted-cv/main/install.sh | bash

REPO="ninejuan/self-hosted-cv"
INSTALL_DIR="${INSTALL_DIR:-$HOME/self-hosted-cv}"
BRANCH="${BRANCH:-main}"

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
NC='\033[0m'

info()  { echo -e "${CYAN}[INFO]${NC}  $*"; }
ok()    { echo -e "${GREEN}[OK]${NC}    $*"; }
warn()  { echo -e "${YELLOW}[WARN]${NC}  $*"; }
fail()  { echo -e "${RED}[ERROR]${NC} $*"; exit 1; }

# ---- Dependency checks ----
check_deps() {
    local missing=()
    command -v docker  >/dev/null 2>&1 || missing+=("docker")
    command -v git     >/dev/null 2>&1 || missing+=("git")

    if [ ${#missing[@]} -gt 0 ]; then
        fail "Missing required tools: ${missing[*]}. Install them first."
    fi

    if ! docker compose version >/dev/null 2>&1; then
        fail "docker compose (v2) is required. Install Docker Compose v2."
    fi

    ok "Dependencies satisfied (docker, docker compose, git)"
}

# ---- Generate secure random string ----
rand_secret() {
    openssl rand -base64 32 2>/dev/null || head -c 32 /dev/urandom | base64
}

# ---- Clone or update repo ----
setup_repo() {
    if [ -d "$INSTALL_DIR/.git" ]; then
        info "Existing installation found at $INSTALL_DIR — pulling latest..."
        git -C "$INSTALL_DIR" fetch origin "$BRANCH" --quiet
        git -C "$INSTALL_DIR" reset --hard "origin/$BRANCH" --quiet
        ok "Updated to latest $BRANCH"
    else
        info "Cloning $REPO into $INSTALL_DIR..."
        git clone --depth 1 --branch "$BRANCH" "https://github.com/$REPO.git" "$INSTALL_DIR"
        ok "Cloned successfully"
    fi
}

# ---- Generate .env ----
setup_env() {
    local env_file="$INSTALL_DIR/.env"

    if [ -f "$env_file" ]; then
        warn ".env already exists — skipping generation. Review it manually if needed."
        return
    fi

    info "Generating .env with secure defaults..."

    local admin_pass
    admin_pass="$(rand_secret | tr -dc 'A-Za-z0-9' | head -c 20)"
    local session_secret
    session_secret="$(rand_secret)"
    local pg_pass
    pg_pass="$(rand_secret | tr -dc 'A-Za-z0-9' | head -c 24)"
    local minio_secret
    minio_secret="$(rand_secret | tr -dc 'A-Za-z0-9' | head -c 24)"

    cat > "$env_file" <<ENVEOF
# Self-Hosted CV — Production Environment
# Generated by install.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")

# App
NODE_ENV=production
APP_PORT=3000
APP_URL=http://localhost
APP_VERSION=0.1.0

# Auth — CHANGE THESE
ADMIN_USERNAME=admin
ADMIN_PASSWORD=${admin_pass}
SESSION_SECRET=${session_secret}
SESSION_IDLE_TIMEOUT=1800
SESSION_MAX_LIFETIME=86400
LOGIN_MAX_ATTEMPTS=5
LOGIN_LOCKOUT_DURATION=900

# Database
POSTGRES_HOST=postgres
POSTGRES_PORT=5432
POSTGRES_DB=cv
POSTGRES_USER=cv_user
POSTGRES_PASSWORD=${pg_pass}

# Redis
REDIS_HOST=redis
REDIS_PORT=6379

# MinIO
MINIO_INTERNAL_ENDPOINT=http://minio:9000
MINIO_PUBLIC_ENDPOINT=/minio
MINIO_ACCESS_KEY=minioadmin
MINIO_SECRET_KEY=${minio_secret}
MINIO_BUCKET=cv-assets
MINIO_USE_SSL=false

# CORS
CORS_ORIGIN=http://localhost

# Update Check
GITHUB_REPO=ninejuan/self-hosted-cv
DISABLE_UPDATE_CHECK=false
UPDATE_CHECK_INTERVAL=21600

# Frontend
VITE_API_URL=/api
API_INTERNAL_URL=http://server:3000
ENVEOF

    chmod 600 "$env_file"
    ok ".env generated with secure random secrets"
}

# ---- Build and start ----
start_stack() {
    info "Building and starting containers (this may take a few minutes on first run)..."
    docker compose -f "$INSTALL_DIR/docker/docker-compose.yml" up -d --build

    info "Waiting for health checks..."
    local retries=0
    local max_retries=30
    while [ $retries -lt $max_retries ]; do
        if docker compose -f "$INSTALL_DIR/docker/docker-compose.yml" ps --format '{{.Status}}' | grep -q "(healthy)"; then
            local healthy_count
            healthy_count=$(docker compose -f "$INSTALL_DIR/docker/docker-compose.yml" ps --format '{{.Status}}' | grep -c "(healthy)" || true)
            if [ "$healthy_count" -ge 4 ]; then
                break
            fi
        fi
        retries=$((retries + 1))
        sleep 5
    done

    if [ $retries -ge $max_retries ]; then
        warn "Some containers may still be starting. Check with: docker compose -f $INSTALL_DIR/docker/docker-compose.yml ps"
    else
        ok "All containers healthy"
    fi
}

# ---- Print summary ----
print_summary() {
    local admin_pass
    admin_pass=$(grep '^ADMIN_PASSWORD=' "$INSTALL_DIR/.env" | cut -d= -f2-)

    echo ""
    echo -e "${GREEN}============================================${NC}"
    echo -e "${GREEN}  Self-Hosted CV — Installation Complete${NC}"
    echo -e "${GREEN}============================================${NC}"
    echo ""
    echo -e "  ${CYAN}Public CV:${NC}    http://localhost"
    echo -e "  ${CYAN}Admin:${NC}        http://localhost/admin"
    echo -e "  ${CYAN}Username:${NC}     admin"
    echo -e "  ${CYAN}Password:${NC}     ${admin_pass}"
    echo ""
    echo -e "  ${YELLOW}Install dir:${NC}  $INSTALL_DIR"
    echo -e "  ${YELLOW}Config:${NC}       $INSTALL_DIR/.env"
    echo ""
    echo -e "  ${CYAN}Commands:${NC}"
    echo "    Stop:       docker compose -f $INSTALL_DIR/docker/docker-compose.yml down"
    echo "    Start:      docker compose -f $INSTALL_DIR/docker/docker-compose.yml up -d"
    echo "    Logs:       docker compose -f $INSTALL_DIR/docker/docker-compose.yml logs -f"
    echo "    Update:     curl -fsSL https://raw.githubusercontent.com/$REPO/main/install.sh | bash"
    echo ""
    echo -e "  ${RED}Save your admin password now. It won't be shown again.${NC}"
    echo ""
}

# ---- Main ----
main() {
    echo ""
    echo -e "${CYAN}Self-Hosted CV — Installer${NC}"
    echo ""

    check_deps
    setup_repo
    setup_env
    start_stack
    print_summary
}

main "$@"
